### ISSUE TITLE
New Feature Stock Transfer with 'In Transit' Mechanism

### ISSUE THREAD

**Issue by f-9t9it** [f-9t9it/optic_store#14]
Stock Transfer  - In Transit Mechanism.
Most software have this feature.
When Stock is transferred from Branch A to Branch B
Then stock is deducted from Branch A and Held in Transit Area until Branch B accepts this transfer.

Manual Solution.
Source warehouse makes stock transfer to a temporary Transit Warehouse
Target warehouse accept it  then stock to be moved from transit warehouse to target warehouse

Issue with manual solution:
User have to create 2 stock transfer document for 1 transaction. Eg: Banch A to Transit  then Transit to Branch B, Which is time consuming and will not give proper report of stock transfers

**Comment by sunhoww** [comment]
We can maybe automate this. For instances, when the Sales Order `workflow_status` changes to and from **In Transit (with Driver)**.
