### ISSUE TITLE
Sales Order Feedback

### ISSUE THREAD

**Issue by f-9t9it** [f-9t9it/optic_store#26]
- [ ] Move Frame Size, Height Type and Height (mm) next to dispenser and lab name section
- [ ] Sales Order Workflow should start according to the Branch location
Keep 1 sales order type, We will give user multiple access rights that branch which have in house process, they will follow the same workflow but they will skip it to the process level manually - Check Workflow diagram

**Comment by f-9t9it** [comment]
- [ ] Sales Order Workflow refactoring as per the Branch and item group.

- [ ] Sales Order Invoice & Print - use Case - Print format have 3 pages eg Collection Slip, Order Form and Lab Order Form.
How can we show Checkbox for each page print.

**Comment by sunhoww** [comment]
- [ ] Add branch field in SO
- [ ] In branch we need to add the Branch Code field and Branch location (Name) will need the name in sales order for printing

**Comment by f-9t9it** [comment]
- [ ] Add multiple payments on 'Invoice & Print' button
- [ ] Add same fields like in sales order
