### ISSUE TITLE
Sales Order Process Flow breaks when user selects old RX 

### ISSUE THREAD

**Issue by f-9t9it** [f-9t9it/optic_store#30]
Example: 
User makes new sales order, Selects Customer, selects old RX of the customer,
Then tries to create new rx, it takes him to the new rx form with pre-filled data
then user enters the new data and save and submit, On submit it does not take him back to the sales order.
this only happen when user selects the old rx in sales order and later try to create new one.

**Comment by sunhoww** [comment]
Issue with JS not built properly on the test server
